### ISSUE TITLE
ModuleNotFoundError: No module named 'zon.number'

### ISSUE THREAD

**Issue by becurrie** [Naapperas/pod#7]
**Describe the bug**
Just installed this while getting a personal project set up with .env validation and ran into this when trying to validate my schema.

See below for the full traceback:

```
Traceback (most recent call last):
  File "..\tortoise_initialize.py", line 3, in <module>
    from app.utils.db import generate_tortoise_config
  File "..\app\utils\db.py", line 1, in <module>
    import settings
  File "..\settings.py", line 5, in <module>
    import zon
  File "...\venv\Lib\site-packages\zon\__init__.py", line 13, in <module>
    from zon.number.float import ZonFloat
ModuleNotFoundError: No module named 'zon.number'
```

**To Reproduce**
- Attempt to import `zon` within a python file or module.

**Expected behavior**
I am able to define zon objects and validate the environment variables loaded through python-dotenv within my project.

**Environment (please complete the following information):**
 - OS: Windows 11 Home
 - Python Version: 3.11.5
 - Version [e.g. 22] 1.0.0 (installed through pip)

**Additional context**
I'm not sure if I am configuring or doing something wrong here, but any help is appreciated :)

**Comment by becurrie** [comment]
@Naapperas Update, maybe something is up with the build process here? I was able to fix this for myself cloning the repository and building it locally, then adding the missing file paths to `zon.egg-info/SOURCES.txt` file and rebuilding with `python -m build`. I'm not familiar with setuptools or packaging python scripts though, but hopefully that helps enough to get a clear idea of what isn't working right now 👍

**Comment by Naapperas** [comment]
Hi @becurrie. First of all, thank you for showing interest in `zon`

I have ever only used this as a local installation (`./build.sh && ./install.sh`) so I might have missed something regarding the published package. Thanks for the heads-up, I will look into the issue.

**Comment by becurrie** [comment]
@Naapperas no problem, I really like the package and it's super useful for my usecase of validating data for my project. One other thing I noticed was after I had fixed my build issues, I was getting some errors about missing the `validate-email` package on my environment, so I think that may need to be included as a dependency when installed through pip as well.

**Comment by Naapperas** [comment]
@becurrie regarding the issue's problem, I will be looking into it.

The `validate-email` problem was happening because I'm not used to publishing packages (specially with the `pyproject.toml` format) and as such did not include the package as a dependency. That should fix that specific problem and is being merged soon.

P.S.: sorry for the delay, college was hectic :)

**Comment by Naapperas** [comment]
> @becurrie regarding the issue's problem, I will be looking into it.
> 
> The `validate-email` problem was happening because I'm not used to publishing packages (specially with the `pyproject.toml` format) and as such did not include the package as a dependency. That should fix that specific problem and is being merged soon.
> 
> P.S.: sorry for the delay, college was hectic :)

Found the issue with the module: there was no `__init__.py` file, hence `number` was not recognized as a module. This will also be fixed in a later release.
